### ISSUE TITLE
FFI slides state windows has 2 ABIs, it's closer to 6

### ISSUE THREAD

**Issue by miguelraz** [ferrous-systems/rust-training#102]
cc @listochkin

**Comment by jonathanpallant** [comment]
I'm not sure it has 6 on one single platform? I was thinking of `C` vs `stdcall` but I could accept changing it to *Windows has __at least__ two* if you want to count `fastball` and `vectorcall`.

**Comment by listochkin** [comment]
[The table here](https://en.wikipedia.org/wiki/X86_calling_conventions#List_of_x86_calling_conventions) lists quite a few, but when I mentioned "closer to 6" I had a few Pascal / Delphi mangled in my head thinking that they were Windows-specific and not Pascal-on-Windows-specific, sorry.

I had to use `stdcall` and `safecall` for COM programming in 2000s, and somehow thought they are Windows things (turns out `safecall` was a Borland invention).

**Comment by jonathanpallant** [comment]
This has been done I think.
